name: AsteorBar
version: '${version}'
main: com.afoxxvi.asteorbarserver.AsteorBar
api-version: 1.13
commands:
  asteorbar:
    description: Reload
    usage: /asteorbar
    permission: asteorbar.use
permissions:
  asteorbar.use:
    default: op
